#!/bin/bash

prefix=G-2301-11-P3

function replace_infile() {
	sed -i .sed -e "s/^#include \"\([a-z_]*\)\.h\"$/#include \"$prefix-\1.h\"/g" $1
	rm $1.sed
}

function process_dir() {
	for f in $(ls $1); do
		replace_infile $1/$f
		mv $1/$f $1/$prefix-$f
	done	
}

function repl_target() {
	sed -i .sed "s/$1/\$(P_NAME)-$1/g" Makefile
	rm Makefile.sed
}

process_dir src
process_dir includes
process_dir tests

for d in $(ls srclib); do
	if [ -d srclib/$d ]; then
		process_dir srclib/$d
	fi
done

repl_target server
repl_target chat
repl_target prsound
repl_target echoserver
repl_target echoclient

sed -i .sed 's/\/test/\/$(P_NAME)-test/g' Makefile
mv Makefile $prefix-makefile
