#ifndef _AS_SS
#define _AS_SS

char _as[] = 
"~:::::::::,,,:,:,,,::IZDNND8OO$7I~$~~~~~~~~~~~~~~~~=====+==+\n"
"::::,::::,,,,,,,,,ZNNDD8NNDDNNDDD8IZ+?~~~::~~~~~~~~~=~======\n"
":,,,,,,,,,,,,,,,.DD888D8DDNNDNNNNNNNND$Z+?:::::~~~~~~~~~====\n"
":,,,,,,,,,,,,,,~8DDNDNDOOOZ888O88DDNNNNNND$~::::~~~~~~~~~===\n"
",,,,,,,,,,,,,==ODDNDOZ7Z$77I7$$III7Z8NNNMNN8~::::~:~~~~~~~==\n"
",,,,,,,,,,,..Z8NNDZ??++=+++++++++??II7$ONNNDO~~::::~::~~~~~~\n"
",,,,,,,,,,..~88N8I++============+++?I77I$DNNNDZ:::::::~~~~~~\n"
",..,,,.,,.,?D88Z?++=====~==~======+??I7I7$8DN$7::::::::~~~~~\n"
",...,,,,,,7888O?++==~~~~~~~~~~====++??II7$$8NDNI:::::::::~::\n"
"...,,,,,,.DDD$??+==~~~~~:~::~~====+++??II$Z8NNNN+::::::::::~\n"
"..,,,,,,,,D8OI?+====~~~~:~::~====++++??II$$8NNNN=::,::::::::\n"
",.,,,,,,,,ZD7I?+======~~~:::~~====+++??I77Z8NNMM7:,:::::::::\n"
",,,,.,,,,,88Z7?++==~~~~~~~~~~=~=~===++?I7$7ONNMM=:,,,:::::::\n"
"...,.,,,..8DOI?+=~~~~~~~~~~=~~~~+??IIIOD8$Z$ONNN=,,,::::::::\n"
"..,,,,,,,,888I?++++++II+===+=+IZZDDND88ZO88OZNNN=,,,,,::::::\n"
"..,,,,:::.8D8I$8OD$DDOZ7??+=?I$O8NO7I7877$8OZNMM7,,:,:,,::::\n"
"..,.,,.,..OD8IZZ77Z??IZ7I+=~+IIZI$=8DIDO7$$OZDNN7I,,,,,:::::\n"
"..,,,..,..ZDD777$8?ODOII??++?I?77I=OOIIZII7ZZDN8$?,,,,,,::::\n"
".,,,.,.,,.+?8I?I7I=?7?????++?II?II++?III?I77Z8OZ?=,,,,,,,:::\n"
",,,,.,,,,,::I?++??+=+?=???++?IIII+++++++++I7ZO8$=+,,,,,,::::\n"
",,,...,,,,:==?++====~=+???++?II7I?+==+++++I7O887+I,,,,,,::::\n"
"..,,,.,,,..~~?+========??+++I7II$?+===+++?I78N8$??,,,,,,::::\n"
",,,,..,,,..++?++====~=???:~~+?III$+=+=++?I7ZDDZ?II,,,,,,,:::\n"
",,.........=~Z+++====+I77???IZZ8O8?+=+?I77$88NI+?7,,,,,,,:::\n"
",,,........===?+++++=??I88Z8D88$77I??+?I77$OOZ,=,,,,,,,,,:::\n"
".,,.........?+?+?++?I$$DOZNI7$8D8Z$OZ$77$I7Z8O,,,,,,,,,:,:::\n"
"..,...........ZI$?7DDOOOZO$7ZODOO88DNND7D$ZOD?,,,:,::,::::::\n"
"..,...........I$87D$DOZ$IIIII77ZO8Z$$8D7NOO8N=::::::::::::::\n"
"..............7$OZO$I??I??===?I7777I77ZD8ZDDD~::~~~~~~:~~:::\n"
"..............,O$OZI?++II7777$$$?II7ZO8DDD8NO~~~~~=~=~~~~~~:\n"
"...............7O8D$Z++=+7OD8D??++$$$OD8O88N+~==+++++====~~~\n"
"................O88DO77++I+7???I7I8$ODDD8DNI+=+????????++==~\n"
"................~8NN88$7O?7?77$$ZOO8NMNDNNNNZ+?I7IIII7II?+==\n"
".............8D,+O$NDDODODDZ8D8DNODMMMNNNDNNIMN777777777I?+=\n"
"............DD,~O$+IONNNNNNNNNMNNNMMNNNNDOMD=MNN$7$777777I?+\n"
"........ ..DD,~$$++=+?8NNNNNNNNNNNNNDD8O$OD~$NNN$$$$$$$$7I?+\n"
" .........ID,:=$$$?~~~~77Z$$ZZI7ZOO$?IIII=~?INNN$$$$$$$$77?+\n"
" ....:DDN8DN,:=7$D?~~~~=+I?=?+I77I?++?I+:~+IDNNMNN$$$Z$$$7I+\n"
"8DNNNNNNDND,.,~I7DI~~~:~==??????++==+?:::=$DNNNMNNNNZZZ$$I?+\n"
"NNNNNNMNND:,,,+$ID?~:~~:~~~=+++++=~~?~??$8NNNNMMNNNMMMMNZI?+\n"
"NNMNNNNDND$8+7M,I+I::~~~:~~~~~===~=.=:~ZMMMMMMMMNNNMMMMMNNNN\n"
"NNNNNNNNND,~~?MD??=I::~:::~~~~~~::~+=NNMMMMMMMMMNNNMMMMMMMMM\n"
"NNMNNNNNNNND:?MNN,::=?+~:::::::,,:?ONNNMMMMMMMMMNNNMMMMMMNMM\n"
"NNNNNNNNN$DDNNNNNN,,=I=II::::,,::=NNNNMMMMMMMNNNNNMMMMMNMMMM\n"
"NNNMNNNNNNNMMDDDDMN,,,.~,7=:::,,=DNMMNNNNNMMMNMNMMMMMMMMMMMM\n"
"NNNNNDDNMNNNNNNNN=DD:,.,.,,I~,:?NNMMNNNNMMMMMMMMMMMMMMMMMMMM\n"
"NNMNNMNNNNNMNNNNNNN8D=,,,, .,,~NNMNNMMMNMMMMMMMMMMMMMMMMMMMM\n"
"NNNNNNNNNNNMMMMNNNNNN=7,,.,,~~NNNNNMMNNMMNMMMMMMMMMMMMMMMMMM\n"
"NNNNNNNNNNNNNNMNNNNNNDN7~,,::NNNNMMMMMMMMMMMMMMMMMMMMMMMMMMM\n"
"             Siento que te haya tocado a ti\n";

#endif
