#!/bin/bash

remove_between_tokens() {
	file=$1
	token=$2
	token_begin="\/\* BEGIN $token \*\/"
	token_end="\/\* END $token \*\/"

	sed -n -e "/$token_begin/{" -e 'p' -e ':a' -e 'N' -e "/$token_end/!ba" -e 's/.*\n//' -e '}' -e 'p' "$file" > "$file.sed"
	mv "$file.sed" "$file"
}

append_file() {
	echo $2 | cat - $1 > $1.temp && mv $1.temp $1
}

init_tests() {
	mkdir -p tests
	templatedir="$( dirname "${BASH_SOURCE[0]}" )"/templates	
	cp "$templatedir/test.c" "$templatedir/testmacros.h" tests
}

create_suite() {
	name=$1
	templatedir="$( dirname "${BASH_SOURCE[0]}" )"/templates

	if [ -z $name ]; then
		echo "Please set a test suite name."
		return
	fi

	cp "$templatedir/testsuite.h" tests/test_$name.h
	cp "$templatedir/testsuite.c" tests/test_$name.c

	sed -i -sbc "s/_testsuite_/test_$name/g"  tests/test_$name.h
	sed -i -sbc "s/_testsuite_/test_$name/g"  tests/test_$name.c

	rm tests/test_$name.h-sbc tests/test_$name.c-sbc

	python "$( dirname "${BASH_SOURCE[0]}" )"/ctest.py addsuitetoglob tests/test.c $name
}

create_test() {
	name=$2
	suite=$1

	if [ -z $name ] || [ -z $suite ]; then
		echo "Please set a test name and corresponding suite."
		return
	fi

	python "$( dirname "${BASH_SOURCE[0]}" )"/ctest.py addtesttosuite tests/test_$suite.c $name
}



save_tests () {
	base="$( dirname "${BASH_SOURCE[0]}" )"
	cp tests/test.c "$base/templates"
	remove_between_tokens "$base/templates/test.c" "TEST REGION"
	sed -i .sed '/#include "test_.*"/d' "$base/templates/test.c"
	rm "$base/templates/test.c.sed"

	cp tests/testmacros.h "$base/templates/"

	test_file_sample=$(ls tests/test_*.c | head -n 1)
	test_file_name=$(basename $test_file_sample | sed 's/\.c//' )
	echo $test_file_sample 
	echo $test_file_name
	cp $test_file_sample "$base/templates/testsuite.c"
	sed -i .sed "s/$test_file_name/\_testsuite\_/g" "$base/templates/testsuite.c"
	rm "$base/templates/testsuite.c.sed"

	remove_between_tokens "$base/templates/testsuite.c" "TEST EXEC"
	remove_between_tokens "$base/templates/testsuite.c" "TESTS"
}

upgrade() {
	templatedir="$( dirname "${BASH_SOURCE[0]}" )"/templates	
	cp "$templatedir/test.c" "$templatedir/testmacros.h" tests

	for test in $(ls tests/test_*.c); do 
		name=$(basename $test | sed -e 's/test\_\([a-zA-Z]*\)\.c/\1/g' )
		echo $name
		python "$( dirname "${BASH_SOURCE[0]}" )"/ctest.py addsuitetoglob tests/test.c $name
	done
}

help() {
	cat << EOF 
Available commands:
	- init: initialize folder and test structure.
	- suite <suitename>: create a test suite with the given name.
	- test <suite> <testname[]>: create various test for the given suite.
	- save: save the changes made in test files in current directory in the template directory.
	- upgrade: upgrade the current installation with changes in template directory.
EOF
}

case "$1" in
	"init") init_tests ;;
	"suite") create_suite $2 ;;
	"test") for t in ${@:3}; do
				create_test $2 $t
			done
			;;
	"save") save_tests ;;
	"upgrade") upgrade ;;
	*) echo "Unrecognized command."
		help ;;
esac
