#!/bin/bash

append_file() {
	echo $2 | cat - $1 > $1.temp && mv $1.temp $1
}

init_tests() {
	mkdir -p tests
	templatedir="$( dirname "${BASH_SOURCE[0]}" )"/templates	
	cp "$templatedir/test.c" "$templatedir/testmacros.h" tests
}

create_suite() {
	name=$1
	templatedir="$( dirname "${BASH_SOURCE[0]}" )"/templates

	if [ -z $name ]; then
		echo "Please set a test suite name."
		return
	fi

	cp "$templatedir/testsuite.h" tests/test_$name.h
	cp "$templatedir/testsuite.c" tests/test_$name.c

	sed -i -sbc "s/_testsuite_/test_$name/g"  tests/test_$name.h
	sed -i -sbc "s/_testsuite_/test_$name/g"  tests/test_$name.c

	rm tests/test_$name.h-sbc tests/test_$name.c-sbc

	python "$( dirname "${BASH_SOURCE[0]}" )"/ctest.py addsuitetoglob tests/test.c $name
}

create_test() {
	name=$2
	suite=$1

	if [ -z $name ] || [ -z $suite ]; then
		echo "Please set a test name and corresponding suite."
		return
	fi

	python "$( dirname "${BASH_SOURCE[0]}" )"/ctest.py addtesttosuite tests/test_$suite.c $name
}

help() {
	cat << EOF 
Available commands:
	- init: initialize folder and test structure.
	- suite <suitename>: create a test suite with the given name.
	- test <suite> <testname>: create a test for the given suite.
EOF
}

case "$1" in
	"init") init_tests ;;
	"suite") create_suite $2 ;;
	"test") create_test $2 $3 ;;
	*) echo "Unrecognized command."
		help ;;
esac
